name: CI - Master
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          echo $(ssh-keyscan 52.186.170.50) > ~/.ssh/known_hosts
          echo $(ssh-keyscan 20.163.169.27) > ~/.ssh/known_hosts
          echo $(ssh-keyscan 20.42.109.8) > ~/.ssh/known_hosts

      - name: Install PM2
        run: npm i pm2

      - name: Deploy
        run: npm run deploy:production
