name: Deploy GATool API
on:
  push:
    branches: [main]


jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install PM2
        run: npm i pm2

      - name: Deploy
        run: npm run deploy:production
